In [35]:
'''
Database & Analytics Programming
Lab 4
'''

'''
1. Exception Handling
a) Create a text file and manually add some data to the file
b) WritePythoncodeto
• open the file for write only access
• attempt to read the contents of the file
c) Note the type of Error that has been raised.
d) Modifyyourcodeto
• use a try / except / finally construct that will catch the exception, print a user-friendly error message, and clean up the file resource
e) Investigate how you would create your own Exception class. Then create your own Exception class and use it in your code from the previous exercise.
'''

from io import UnsupportedOperation

# e - creating Exception class
class OwnException(UnsupportedOperation):
    """Unsupported operation called on the file"""
    pass


# a - created a file exe1.txt file with path - /Users/sobil/Documents/MSC/Sem 1/Database & Analytical Programming/Lab/Lab - 4/exe1.txt

# b
try :
    file = open("/Users/sobil/Documents/MSC/Sem 1/Database & Analytical Programming/Lab/Lab - 4/exe1.txt","w")
    content = file.read()
    print(content)
# c, d
except OwnException as ex :
    print("We can't read the file in write mode.")
finally :
    file.close()
    print("file closed")
    


file closed


UnsupportedOperation: not readable

In [40]:
'''
2. Numpy Exercise A
a) Create an array with the arange function and reshape the array as follows: b = arange(24).reshape(2,3,4)
This gives us a 3-dimensional data structure – you can think of it as being like 2 spreadsheet sheets where each sheet contains 3 rows of data and each row contains 4 columns.
Using indexing and slicing perform the following tasks:
i) Choose the first set of 3 rows and 4 columns of data
ii) Choose the second row of data from the second set of 3 rows of data
iii) Choose all the data from the second column for both the first and second
sets of rows and columns of data
b) Usetheravelfunctiontoflattenthedata.What’sthedifferencebetweenravel and flatten?
c) Reshape the data so that there are 6 rows of 4 columns per row.
d) Getthetransposeofthenewdatastructure.
e) Restack the rows of the transposed data structure in reverse order (hint: look at
the row_stack function).
f) Split the resulting data structure horizontally (hint: look at the hsplit function).
'''

# a
import numpy as np

b = np.arange(24).reshape(2,3,4)
print(b)



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [45]:
# a.i
b = np.arange(24).reshape(2,3,4)
print(b[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
# a.ii
b = np.arange(24).reshape(2,3,4)
print(b[1][1])

[16 17 18 19]


In [64]:
# a.iii
b = np.arange(24).reshape(2,3,4)
b[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [80]:
# b) Usetheravelfunctiontoflattenthedata.What’sthedifferencebetweenravel and flatten?
import numpy as np
b = np.arange(24).reshape(2,3,4)

#b.ravel()
#print("Flatten")
print(b.ravel())
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [84]:
# c) Reshape the data so that there are 6 rows of 4 columns per row.
import numpy as np
b = np.arange(24).reshape(2,3,4)

c = b.reshape(6,4)
print(c)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [86]:
# d) Getthetransposeofthenewdatastructure.
b = np.arange(24).reshape(2,3,4)

c = b.reshape(6,4)
t = c.transpose()

print(t)

[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


In [95]:
# e) Restack the rows of the transposed data structure in reverse order (hint: look at
# the row_stack function).
import numpy as np
b = np.arange(24).reshape(2,3,4)

c = b.reshape(6,4)
t = c.transpose()

flp = np.flip(t)
print(flp)

rstck = np.vstack(flp)

print(rstck)

[[23 19 15 11  7  3]
 [22 18 14 10  6  2]
 [21 17 13  9  5  1]
 [20 16 12  8  4  0]]
[[23 19 15 11  7  3]
 [22 18 14 10  6  2]
 [21 17 13  9  5  1]
 [20 16 12  8  4  0]]
