# 1. Exception Handling

In [3]:
# 1.a
f = open("demo.txt", "w")
f.write("Mary Jones, 34, mary@example.com, manager \n")
f.write("Peter Adams, 45, peter@example.com, sales \n")
f.close()

In [4]:
f = open("demo.txt", "r")
print(f.read())
f.close()

Mary Jones, 34, mary@example.com, manager 
Peter Adams, 45, peter@example.com, sales 



In [5]:
f = open("demo.txt", "w")
print(f.read())
f.close()

UnsupportedOperation: not readable

In [ ]:
import sys
import io

try:
    f = open("demo.txt", "w")
    print(f.read())    
except io.UnsupportedOperation:
    print("A type of 'UnsupportedOperation' exception was triggered.\nThis is because you have opened your file in a write mode, while you are trying to read it !")
except:
    ("Other type of error " + sys.exc_info()[2])
finally:
    f.close()

In [ ]:
class MyCustomException(io.UnsupportedOperation):
    pass


try:
    f = open("demo.txt", "w")
    
    raise MyCustomException('You have opened your file in an incompatible mode')    
    print(f.read())    
    
except io.UnsupportedOperation:
     print("Handled by '{}': {}".format(sys.exc_info()[0], sys.exc_info()[1]))
except:
    print("Other type of error {}".format(sys.exc_info()[2]))
finally:
    f.close()

# 2. Numpy Exercise A

In [1]:
# 2.a
import numpy as np
b = np.arange(24).reshape(2,3,4)
print(f"2.a.i => {b[0]}")
print(f"2.a.ii => {b[1,1,:]}")
print(f"2.a.iii => {b[:,1,:]}")
# 2.b
b = b.ravel()
print(f"2.b => {b}")
# 2.c
b = b.reshape(6,4)
print(f"2.c => {b}")
#2.d
b = b.T
print(f"2.d => {b}")
# 2.e
b = np.flip(b)
print(f"2.e => {b}")
# 2.f
b = np.hsplit(b,2)
print(f"2.f => {b}")

2.a.i => [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2.a.ii => [16 17 18 19]
2.a.iii => [[ 4  5  6  7]
 [16 17 18 19]]
2.b => [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2.c => [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2.d => [[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
2.e => [[23 19 15 11  7  3]
 [22 18 14 10  6  2]
 [21 17 13  9  5  1]
 [20 16 12  8  4  0]]
2.f => [array([[23, 19, 15],
       [22, 18, 14],
       [21, 17, 13],
       [20, 16, 12]]), array([[11,  7,  3],
       [10,  6,  2],
       [ 9,  5,  1],
       [ 8,  4,  0]])]


# 3. NumPy Exercise B

In [ ]:
import numpy as np
# 3.a
aapl = np.loadtxt(fname="/Users/sobil/Documents/MSC/Sem 1/Database & Analytical Programming/Lab/Lab - 4/AAPL.csv", delimiter=",", usecols=(4,6), skiprows=1)
print(f"3.a :: aapl[5,7] => {aapl[0:5,:]}")
# 3.b
aapl_weighted_price = np.average(aapl[:,0], axis= 0, weights= aapl[:,1])
print(f"3.b :: aapl_weighted_price => {aapl_weighted_price}")

# 3.c
print(f"3.c :: median => {np.median(aapl[:,0])}")

# 3.d
print(f"3.d :: variance => {np.var(aapl[:,0])}")

# 3.e
aapl = np.loadtxt("/Users/sobil/Documents/MSC/Sem 1/Database & Analytical Programming/Lab/Lab - 4/AAPL.csv", delimiter=",", usecols=(2,3), skiprows=1)
print(f"3.e :: aapl[3,4] => {aapl[0:5,:]}")

# 3.f
print(f"3.f :: highest high => {np.max(aapl[:,0])}")
print(f"3.f :: & lowest low => {np.min(aapl[:,1])}")

# 3.g
aapl = np.loadtxt(fname="/Users/sobil/Documents/MSC/Sem 1/Database & Analytical Programming/Lab/Lab - 4/AAPL.csv", delimiter=",", usecols=(4), skiprows=1)
msft = aapl = np.loadtxt(fname="/Users/sobil/Documents/MSC/Sem 1/Database & Analytical Programming/Lab/Lab - 4/MSFT.csv", delimiter=",", usecols=(4), skiprows=1)
print(f"3.g :: aapl[5] => {aapl[0:5]}")
print(f"3.g :: & msft[5] => {aapl[0:5]}")

# 3.h
print(f"3.h :: covariance => {np.cov(aapl,msft)}")

# 3.i
print(f"3.i :: diagnol => {np.cov(aapl,msft).diagonal()}")

# 3.j
print(f"3.h :: correlation => {np.cov(aapl,msft)}")


# 4. Regular Expresssions

In [ ]:
import re
regex = r"http[s]?:\/\/\w+\.com?"
testData = "https://google.comhttp://google.comhtts://google.comhttp:/google.com"
x = re.findall(regex, testData)
print(x)

# 5. Text Analytics

In [7]:
from nltk.tokenize import sent_tokenize
text="Today is a great day. It is even better than yesterday. And yesterday was the best day ever."
sent_tokenize(text)

['Today is a great day.',
 'It is even better than yesterday.',
 'And yesterday was the best day ever.']

In [8]:
from nltk.tokenize import word_tokenize
word_tokenize(text)

['Today',
 'is',
 'a',
 'great',
 'day',
 '.',
 'It',
 'is',
 'even',
 'better',
 'than',
 'yesterday',
 '.',
 'And',
 'yesterday',
 'was',
 'the',
 'best',
 'day',
 'ever',
 '.']

In [18]:
from nltk.corpus import wordnet

sym = wordnet.synsets('love')
sym
sym[0].definition()
sym[0].examples()

synonyms=[]
for syn in wordnet.synsets('AI'):
    for lemma in syn.lemmas():
        synonyms.append(lemma.name())
synonyms

['Army_Intelligence',
 'AI',
 'artificial_intelligence',
 'AI',
 'three-toed_sloth',
 'ai',
 'Bradypus_tridactylus',
 'artificial_insemination',
 'AI']